apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-rps-deployment
  labels:
    app: flask-rps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-rps
  template:
    metadata:
      labels:
        app: flask-rps
    spec:
      containers:
      - name: flask-rps
        image: ibraheemcisse/flask-rps-app:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
